## 05 `numpy.array` 基本操作

In [1]:
import numpy as np
np.random.seed(0)

x = np.arange(10)

In [2]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
X = np.arange(15).reshape((3, 5))

In [4]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### ``numpy.array`` 的基本属性

In [5]:
# n-dimension，查看是几维数组
x.ndim

1

In [6]:
X.ndim

2

In [7]:
x.shape

(10,)

In [8]:
X.shape

(3, 5)

In [9]:
x.size

10

In [10]:
X.size

15

### ``numpy.array`` 的数据访问

In [11]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
x[0]

0

In [13]:
x[-1]

9

In [14]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
# 不建议！这样写对于访问一个元素是没问题的，但是在numpy中不建议这么做，具体看下文
X[0][0] 

0

In [16]:
X[0, 0]

0

In [17]:
X[0, -1]

4

In [18]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
x[0:5]

array([0, 1, 2, 3, 4])

In [20]:
x[:5] # 切片可以有默认值，例如冒号左边不填写的话，默认值为0，即从头开始访问

array([0, 1, 2, 3, 4])

In [21]:
x[5:] # 冒号右边不填写的话，则默认访问到结尾，也就是从5到最后一个数

array([5, 6, 7, 8, 9])

In [22]:
x[4:7]

array([4, 5, 6])

In [23]:
x[::2] # 从第0个元素开始，一直到最后，步长为2

array([0, 2, 4, 6, 8])

In [24]:
x[1::2] # 从第1个元素开始，一直到最后，步长为2

array([1, 3, 5, 7, 9])

In [25]:
x[::-1] # 范围：所有元素，步长为-1，也就是从最后一个元素开始取

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [26]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [27]:
"""
切片语法，同样可以运用在2维数组中，以下用法访问的是前2行的前3列,相当于
第1维取的是一个切片：前2行，
第2维取的是另一个切片，前3列，
两者组合在一起，构成一个2*3的数组
"""

X[:2, :3] 

array([[0, 1, 2],
       [5, 6, 7]])

In [28]:
"""
如果使用两个方括号的形式来表达，得到的结果并非我们所期望的。
首先计算X[:2]得到X数组的前两行，然后再在这个中间结果的基础上再取前3行（计算[:3]），因为中间结果只有2行，因此最终结果只能取到前2行。
因此，使用两个[]来索引2维数组，并不能得到我们想要表达的语义。
结论：如果切片需要作用在不同的维度上，必须使用“，”运算符。
"""

X[:2][:3] # 结果不一样，在numpy中使用","做多维索引

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [29]:
tmp = X[:2]
tmp

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [30]:
result = tmp[:3]
result

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [31]:
"""
访问前两行，
对于每一行都想访问从头到尾但是间隔为2的元素
"""
X[:2, ::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [32]:
"""
整个访问过程，
行从最后一行到第一行倒着数，
对于每一行而言，列也是从最后一列到第一列倒着数
"""
X[::-1, ::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [33]:
"""
对于多维矩阵，有时需要做降维处理，
例如，只想取第1行，使用X[0]固然可以，
当然我们也可以使用2维的表达法，使用X[0, :]（行取第1行，列取从头到尾）
"""
X[0]

array([0, 1, 2, 3, 4])

In [34]:
X[0, :] # 从矩阵变成了一个1维的数组

array([0, 1, 2, 3, 4])

In [35]:
X[0, :].ndim # 进一步验证，维数确实为1

1

In [36]:
"""
取某1列怎么处理？此时就不能简单的只使用1个方括号了
"""

X[:, 0] # 取第1列。做法：“行”这个维度取所有行，对于每1行而言，“列”这个维度只取第一列

array([ 0,  5, 10])

In [37]:
X[:, 0].ndim # 进一步验证，确实是一个1维数组

1

### Subarray of ``numpy.array``

In [38]:
subX = X[:2, :3] # 拿到X的一个子矩阵
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [39]:
subX[0, 0] = 100 # 对子矩阵的元素进行修改，注意观察原来的矩阵X
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [40]:
"""
修改X的子矩阵，导致X矩阵也发生了变化。
对Python原生的list进行切片操作，实际上会创建一个全新的矩阵，也就是说subX合原来的X是没有关系的。
但是，在numpy中，两者是存在关联的。
由下面的结果，很容易发现，X的第0行第0列，也变成了100。

对于numpy来说，优先考虑的是效率，因此对于取“子矩阵”的操作，numpy使用的是类似引用的方式来获得的。
此时，修改子矩阵的元素，会影响原矩阵，同理，修改原矩阵，也会影响子矩阵。
"""
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [41]:
X[0, 0] = 0
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [42]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [43]:
"""
创建与原来矩阵不相关的子矩阵
"""
subX = X[:2, :3].copy() 

In [44]:
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [45]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### Reshape

In [46]:
x.shape

(10,)

In [47]:
x.ndim

1

In [48]:
x.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [49]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
A = x.reshape(2, 5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [51]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
B = x.reshape(1, 10)
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [53]:
B.ndim

2

In [54]:
B.shape

(1, 10)

In [55]:
"""
有的时候，我们在做reshape的时候，只想指定1个维度的数据，对于另外1个维度的数据，我们希望计算机帮我们自动算出来。
例如，如果我们只想要10行，至于每一行有多少个元素，我们并不关心。
如果x有10个元素，那么每一行就应该有1个元素；如果x有100个元素，那么每一行就应该有10个元素。
但这都不是我想要关心的，我关心的只在于x经过reshape后，有10行，此时，对于reshpae函数中的“列”参数可以传入-1
"""

x.reshape(10, -1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [56]:
"""
下面的例子，我们不管x经过reshape后有多少行，我们关心的点在于每一行需要有10个元素，也就是有10列。
"""
x.reshape(-1, 10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [57]:
x.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [58]:
"""
10不能被3整除，会报错
"""
x.reshape(3, -1)

ValueError: cannot reshape array of size 10 into shape (3,newaxis)